#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define LEADERBOARD "CgkIqtTF34sNEAIQAA"

#define DISPLAY_TIME_SPLASH_SCENE 0.8
#define TRANSITION_TIME 0.4

#define BIRD_COLLISION_BITMASK 0x000001
#define OBSTACLE_COLLISION_BITMASK 0x000002
#define POINT_COLLISION_BITMASK 0x000003

#define SPEED_RIGHT 3
#define SPEED_LEFT -3
#define SPEED_UP 18

#define CHARACTER_SIZE 48.0
#define CHARACTER_FORMS 5
#define BARRIERS_HEIGHT 33.0
#define CLOUDS_HEIGHT 111.0
#define CLOUDS_SHIFT 18.0
#define MIDDLE_BARRIER_SHIFT 132.0
#define LEFT_RIGHT_BARRIER_SHIFT 126.0
#define LEFT_RIGHT_BARRIER_INDENT 66.0
#define LEFT_RIGHT_BARRIER_DISTANCE 174.0
#define BUTTON_SHIFT_RATE 33.0
#define BUTTON_SHIFT 96.0
#define BUTTON_UP_SHIFT 36.0
#define CHOOSE_BUTTON_RIGHT_SHIFT 24.0
#define CHOOSE_BUTTON_DOWN_SHIFT 54.0

#define SCORE_DIGITS_AMOUNT 4
#define SCORE_SHIFT 18

#define NUMBERS_SPACING 3

#define SMALL_NUMBERS_WIDTH 21
#define SMALL_NUMBERS_HEIGHT 30
#define SMALL_NUMBERS_SPACING NUMBERS_SPACING

#define BIG_NUMBERS_WIDTH 36
#define BIG_NUMBERS_HEIGHT 51
#define BIG_NUMBERS_SPACING NUMBERS_SPACING

#endif // __DEFINITIONS_H__
